[package]
name = "folder-size"
version = "0.1.0"
edition = "2021"

[dependencies]
cursive = { version = "0.20", default-features = false, features = ["crossterm-backend"] }
cursive_table_view = "0.14"
clap = { version = "4.1.4", features = ["derive"] }

[dev-dependencies]
mockall = "0.11.3"
