use lazy_static::lazy_static;
use regex::{Error, RegexSet};

lazy_static! {
    pub(crate) static ref PATTERNS: Vec<(&'static str, Result<RegexSet, Error>)> = vec![
        //KEEP IN ALPHABETICAL ORDER WITHIN EACH CATEGORY BY 1st FOLDER NAME, IGNORING 'A' AND 'THE'
        //GAMES
        ("Shoot xenos. Get some!", RegexSet::new([r"\\Aliens Fireteam Elite$"])),
        ("Get killed by robots while hiding from xenomorphs.", RegexSet::new([r"\\Alien Isolation$"])),
        ("This was the one you wanted right? Not Dead Space...?", RegexSet::new([r"Callisto Protocol[\w\s]*$"])),
        ("Meet American teenagers online so that they can call you gay.", RegexSet::new([r"\\Call of Duty[\w\s]*$"])),
        ("Enter The Oldest House.", RegexSet::new([r"\\Control$"])),
        ("Shoot other people, even ones you like.", RegexSet::new([r"\\Counter-Strike Global Offensive$"])),
        ("Gonks, Corpos and Netrunners. I had sex in this game and won a highly dangerous tactical assault dildo.", RegexSet::new([r"\\(?i)cyberpunk2077[\w\s]*$"])),
        ("A dreadful, awful, beautiful game that will take over your life and make you doubt your ability to carry out basic human functions.", RegexSet::new([r"\\(?i)Dark Souls[\w\s]*$"])),
        ("Solve problems by walking on the ƃuıןıǝɔ.", RegexSet::new([r"\\(?i)darq$"])),
        ("So. Many. Limbs!", RegexSet::new([r"\\Dead Space"])),
        ("Using words would only make me seem foolish.", RegexSet::new([r"\\(?i)Death[\w\s]*Stranding$"])),
        ("Grind Guardian!", RegexSet::new([r"\\Destiny[\w\s]*$"])),
        ("Dungeon-crawling roguelike top-down hack and slash demon slaughter.", RegexSet::new([r"\\(?i)diablo[\w\s]*$"])),
        ("Very... well, talky. Expect it to say \"end stage capitalism\" at any time. Has a hipster beard.", RegexSet::new([r"\\Disco Elysium$"])),
        ("There are rats in this game, like, a lot of rats.", RegexSet::new([r"\\Dishonored[\w\s]*$"])),
        ("The never ending suffering of Doom guy.", RegexSet::new([r"\\(?i)doom[\w\s]*$"])),
        ("A naked pumpkin-headed guy.", RegexSet::new([r"\\ELDEN RING$"])),
        ("Dog based post nuclear recreation engine.", RegexSet::new([r"\\Fallout[\w\s]*$"])),
        ("Since the first Final Fantasy there has been a long line of fantasy themed sequels.", RegexSet::new([r"\\(?i)Final Fantasy[\w\s]*$"])),
        ("Scrub!", RegexSet::new([r"\\Fortnite$"])),
        ("I have no idea why this game is so popular, and at this point I'm afraid to ask.", RegexSet::new([r"\\Genshin Impact[\w\s]*$"])),
        ("\"Keep up boy!\"", RegexSet::new([r"\\GodOfWar$"])),
        ("Trevor Philips approves.", RegexSet::new([r"\\GTA[\w\s\.]*$"])),
        ("Master Chief Sir!", RegexSet::new([r"\\(?i)Halo[\w\s\.]*$"])),
        ("Diabolically good hell-based beat-shooter.", RegexSet::new([r"\\Metal Hellsinger$"])),
        ("Low-rez Roblox.", RegexSet::new([r"\\Minecraft[\w\s\.]*$"])),
        ("Death Stranding on the moon.", RegexSet::new([r"\\Moon Runner$"])),
        ("I know nothing about this game.", RegexSet::new([r"\\League of Legends"])),
        ("Smart and stylish turn-based tactical RPG, featuring female warriors who are fully clothed, in a possible video game first.", RegexSet::new([r"\\Othercide$"])),
        ("A bit memey, but fine.", RegexSet::new([r"\\Overwatch[\w\s\.]*$"])),
        ("I've never even heard of Wipeout...", RegexSet::new([r"\\Redout\d*$"])),
        ("The Umbrella Corporation's finest!", RegexSet::new([r"\\(?i)resident\s*evil[\w\s\.]*$"])),
        ("It's déjà vu all over again...", RegexSet::new([r"\\Returnal$"])),
        ("Free Minecraft.", RegexSet::new([r"\\Roblox[\w\s\.]*$"])),
        ("Awesome rollerskating and violence, bullet-time ass-kicking-tricking game!", RegexSet::new([r"\\(?i)rollerdrome$"])),
        ("Soccer with cars? Would improve the Premiership...", RegexSet::new([r"\\(?i)Rocket[\s]*League$"])),
        ("Destructible bullet-time shooter. Pretty good.", RegexSet::new([r"\\SeveredSteel$"])),
        ("Lead someone else's boring life.", RegexSet::new([r"\\(?i)Sims[\w\s]*$",r"\\(?i)TheSims[\w\s]*$"])),
        ("Wait... I thought this was The Witcher?", RegexSet::new([r"\\(?i)skyrim[\w\s]*$"])),
        ("Hate sleep, but love galactic domination? Then this is the game for you.", RegexSet::new([r"\\Stellaris$"])),
        ("Well, you play a cat. With a backpack. Surprisingly realistic.", RegexSet::new([r"\\Stray$"])),
        ("Fighting in giant robots, except when you need to get out and run around.", RegexSet::new([r"\\Titanfall[\w\s]*$"])),
        ("I've heard it's pretty good.", RegexSet::new([r"\\Valorant[\w\s]*$"])),
        ("Grind Guardian, I mean, Tenno!", RegexSet::new([r"\\Warframe[\w\s]*$"])),
        ("The light hearted adventures of Geralt and Ciri. Absolutely no fully functioning brothels.", RegexSet::new([r"\\The Witcher[\w\s]*$"])),
        ("Second Life in Middle Earth.", RegexSet::new([r"\\(?i)World Of Warcraft$"])),

        //SMART-ARSE
        ("Some assembly required.", RegexSet::new([r"\\assembly$"])),
        ("Das.", RegexSet::new([r"\\Boot$"])),
        ("I'm something of a scientist myself.", RegexSet::new([r"\\Elixir$", r"\\Julia$", r"\\R$", r"\\ucm-windows$", r"\\Python$", r"\\erl-[\w\s\.]*$"])),
        ("Get REALLY good at programming!", RegexSet::new([r"\\(?i)Exercism$"])),
        ("Small washbasins in churches.", RegexSet::new([r"\\Fonts$"])),
        ("An old man, liable to be rude and uncooperative, who only understands obscure jargon.", RegexSet::new([r"\\Git$"])),
        ("I love globs...", RegexSet::new([r"\\Globalization$"])),
        ("Whoogle? Never heard of them.", RegexSet::new([r"\\Google$"])),
        ("The best IDEs.", RegexSet::new([r"\\(?i)Jetbrains$"])),
        ("Reminds me of my grandpa: old, smelly and everyone is surprised to find he's still kicking around.", RegexSet::new([r"\\Internet Explorer$"])),
        ("Office software, written by the hairless drones of the Microsoft hive.", RegexSet::new([r"\\Microsoft Office$"])),
        ("H4X0R!", RegexSet::new([r"\\Microsoft Visual Studio$"])),
        ("R0XX0R", RegexSet::new([r"\\Razer$"])),
        ("The best DAW.", RegexSet::new([r"\\Renoise[\w\s\.]*$"])),
        ("Game or 🦀?", RegexSet::new([r"\\(?i)rust[\w\s]*$"])),
        ("As in \"Wow, this is what you decided to name the 32bit binary directory?\"", RegexSet::new([r"\\SysWOW64$"])),
        ("Xbox games, maybe? I mean, I'm just guessing...", RegexSet::new([r"\\XboxGames$"])),

        //USEFUL INFO
        ("Apparently something to do with sd cards.", RegexSet::new([r"\\BayHubTech$"])),
        ("Games. Has its own app to add and remove them.", RegexSet::new([r"\\Epic Games$"])),
        ("Used by Windows to store contents of RAM during sleep or hibernate mode.", RegexSet::new([r"\\hiberfil.sys"])),
        ("Music production software.", RegexSet::new([r"\\(?i)native instruments$"])),
        ("Graphics stuff.", RegexSet::new([r"\\(?i)nvidia[\w\s]*$"])),
        ("Virtual memory file used by Windows.", RegexSet::new([r"\\pagefile.sys"])),
        ("Database software.", RegexSet::new([r"\\(?i)PostgreSQL$"])),
        ("Programs might store data here 🙄", RegexSet::new([r"\\ProgramData$"])),
        ("Your apps and programs. Manage with \"Settings/Apps/Installed apps\" in Windows.", RegexSet::new([r"\\Program Files$"])),
        ("Your apps and programs - pre 1986 (jk).", RegexSet::new([r"\\Program Files \(x86\)$"])),
        ("Audio stuff.", RegexSet::new([r"\\Realtek$"])),
        ("Your data, such as Documents and Downloads.", RegexSet::new([r"\\Users$"])),
        ("Often full of stuff you have downloaded, but don't need anymore.", RegexSet::new([r"\\Users\\[\w\s-]+\\Downloads$"])),
        ("Games! Manage these with the Steam app.", RegexSet::new([r"\\Steam$", r"\\(?i)SteamLibrary$"])),
        ("In here...", RegexSet::new([r"\\Steam\\steamapps$", r"\\(?i)SteamLibrary\\steamapps$"])),
        ("Keep going...", RegexSet::new([r"\\Steam\\steamapps\\common$", r"\\(?i)SteamLibrary\\steamapps\\common$"])),
        ("This is probably your operating system. Use Windows utilities to manage contents.", RegexSet::new([r"\\Windows$"])),
        ("Don't even think about it.", RegexSet::new([r"\\Windows\\System32$"])),
        ("Do not touch.", RegexSet::new([r"\\Windows\\WinSxS$", r"\\System Volume Information$"])),
        ("Stores links to the files you have put into the Recycle Bin.", RegexSet::new([r"\\\$Recycle.Bin$"])),
        ("Used to diagnose problems with system reset or refresh.", RegexSet::new([r"\\\$SysReset$"])),
        ("System folder used if needed to roll back updates. Will be empty if system is healthy.", RegexSet::new([r"\\\$WinREAgent$"])),
    ];
}
